app:
  endpoint:
    version: v1

server:
  port: 10098
  servlet:
    context-path: /prueba-wolox

spring:
  main:
    lazy-initialization: false
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba_wolox
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate-dialect: org.hibernate.dialect.PostgreSQLDialect
